Added dataErase on refusal event and new refusal type
ONSdigital/ssdc-shared-events pull request #19
Opened 2022-02-16 10:59 UTC by ryangrundy7

# Motivation and Context

During a survey someone might want to withdraw from a survey after previously agreeing to take part. This PR adds in a new withdrawal type to the refusal event. If someone asks for us to remove all their sensitive data, we can now do that with the eraseData field on the event as well  

# What has changed

- Withdrawal_refusal type on refusal event
- Can request for your sensitive data to be removed 
# How to test?

# Links

[Trello](https://trello.com/c/q8cx1tZn/)

2022-02-16 13:46 UTC, AdamHawtin commented on event_dictionary/0.6.0-DRAFT/refusal.schema.json
> +          "description": "Data erasure request has been received",
Worth adding that this flag is optional, defaulting to `false` if it's not set.

2022-02-17 08:19 UTC, AdamHawtin approved these changes

2022-02-17 09:42 UTC, AdamHawtin requested changes
The case update schema also has a refusal type enum which needs updating. Can we factor out common enums like this to be reused?

2022-02-18 11:22 UTC, LukeLoze1 approved these changes

2022-02-18 12:13 UTC, merged